### ISSUE TITLE
Cryptic Error Message when Exposure Notification API is not available

### ISSUE THREAD

**Issue by alexandredeleze** [DP-3T/dp3t-app-android-ch#51] opened 2020-05-26 07:29 UTC
I tried the commit 3dd348c025f82434fc6183be7c2262516d5f7d0e and because by Honor 8X didn't receive the update from Google, I don't have the exposure notification api. When I try to activate the tracing an alert pop up with I think the original error message "17: API: Nearby.Exposure_NOTIFICATION_API is not available on this device. Connection failed with: ...". Maybe it can be good to modify this error message for the user.

**Comment by zukunft** [comment] 2020-05-26 09:29
I have the same with a OnePlus 5T and LineageOS. Would be nice if there would be alse a "non GAEN" Version.

**Comment by micahwilhelm** [comment] 2020-05-26 12:18
I get the same error on my Moto X 2nd Gen running LineageOS 16.0 (based on Android 9)  when trying to activate tracing:  
> 17: API: Nearby.EXPOSURE_NOTIFICATION_API is not available on this device. Connection failed with: ConnectionResult{statusCode=UNKNOWN_ERROR_CODE(39501),  resolution=null, message=null}"

**Comment by senic35** [comment] 2020-05-26 13:56
Same error on my OnePlus 7Pro with OxygenOS 10.0.0.5

**Comment by michalogit** [comment] 2020-05-26 18:59
Same error, huawei p20 lite, android 9

![Screenshot_20200526_205217_ch admin bag dp3t](https://user-images.githubusercontent.com/6973599/82939164-3cf63a00-9f93-11ea-9bae-96d1ea73c026.jpg)

**Comment by Continuum-Q** [comment] 2020-05-27 07:49
Same issue on Google Pixel 4XL on May 5th security update. 
![Screenshot_20200527-094438](https://user-images.githubusercontent.com/65154954/82992361-5339df80-9fff-11ea-8e9f-b376cf041dab.png)

**Comment by LarsBaertschi** [comment] 2020-05-27 09:03
Seems to be linked when the app is not signed with the official certificate (e.g. when you build it from source and install it on your own device). After downloading the correct signed version from the Play Store, the error message disappeared (only for that version of the app).

Would be cool if we could also build it ourselves to debug, test and analyze it fully, instead of relying on the Play Store build.

**Comment by kplanz** [comment] 2020-05-27 13:35
The same is true for the calibration app (in the SDK project) btw.

Logcat shows the following message: 
> ExposureNotification: Reject the api access due to the caller is not whitelisted

**Comment by stefanriesen** [comment] 2020-05-28 12:41
Get the same message here in the follwoing environment
* Nokia 7.2
* Android 10 (Build Nr. 00WW_2_270_SP01)
* Security Patches 05/2020
* Play Services 20.18.17 (120400-311416286)
* SwissCovid App Version 1.0-pilot installed through Play Store

**Comment by naspert** [comment] 2020-05-28 15:46
same here with Fairphone 2 
Android 7.1 and app installed through Play Store

**Comment by beckm-ethz** [comment] 2020-05-28 17:56
Also got the UNKNOWN_ERROR_CODE(39501) on:
- Nokia 7.1
- Android 10 (Build Nr. 00WW_4_08B_SP05)
- Security Patches 05/2020
- Play Services 20.18.17 (120400-311416286)
- SwissCovid App Version 1.0-pilot, 0.5.0 (Play Store (Early Access))
- Using a second user on the device where the main user had a wrong country (#52)

**Comment by Flash1232** [comment] 2020-05-30 15:44
Same issue here on:
- OnePlus 5T
- Android 10 (Build Nr. A5010_43_200513) / OxygenOS 10.0.0
- Security Patches 05/2020
- Play Services 20.15.16 (120400-309763488) / Play System Update 2020-05-01
- SwissCovid App Version 1.0.1-pilot

**Comment by LoremoCH** [comment] 2020-06-01 13:20
Same or similar problem on Fairphone 2

- Fairphone 2
- Android 7.1.2
- Security Patches 2019-10-05
- Play Services 20.18.17
- SwissCovid App Version 1.0.1-pilot, 0.5.1 (Installed by Google Play Store)

Most of the time it does not work right at the start. Sometimes the app briefly shows that it is working normally. But after a few minutes the following message appears.

![Screenshot_20200601-150437](https://user-images.githubusercontent.com/6465374/83412577-a0acb700-a41a-11ea-84a4-f95b561a5b98.png)

![Screenshot_20200601-151051](https://user-images.githubusercontent.com/6465374/83412613-b5894a80-a41a-11ea-9ef4-01d9af17fca0.png)

![Screenshot_20200601-105657](https://user-images.githubusercontent.com/6465374/83412790-04cf7b00-a41b-11ea-93a0-a9f44bad582f.png)

**Comment by simonpra** [comment] 2020-06-04 14:09
Got the same yesterday on my Honor 10. With last _Google Play Service 20.18.something_.
Updated with _Google Play Service 20.21.15 (bêta)_, at first same error, but today everything's working ;-)

Try updating the _Google Play Service_ to the **bêta** version (must be registered for bêta preview).

- Honor 10
- Android 9
- Last security update (april 2020)
- Google Play Services 20.21.15 (bêta)
- SwissCovid App Version 1.0.1-pilot, 0.5.1 (Installed by Google Play Store)

**Comment by simonroesch** [comment] 2020-06-07 21:02
There were several issues here:

ApiException 17 with statusCode=39501 was an error in the ExposureNotification framework of Google that happened on devices not supporting [bluetooth multiple advertisement](https://developer.android.com/reference/android/bluetooth/BluetoothAdapter#isMultipleAdvertisementSupported()). This issue has been fixed now by Google and should no longer happen. If it still does happen. on your device, please open a new issue and include the app version, the Google Play Services version as well as the output of
`adb shell dumpsys activity provider com.google.android.gms.chimera.container.GmsModuleProvider | grep 'nearby_en'`

ApiException 17 with statusCode=39507 is due to Google checking the app signature when using the ExposureNotification framework. Only our production signature (used for PlayStore builds only) is whitelisted, therefore it is currently not possible to use the ExposureNotification framework when the app is not downloaded from the PlayStore but build individually. We are hoping for a solution from Google to enable developers to use the framework also with non-whitelisted apps (signatures). We are also working on reproducible builds that will allow to verify that the APK from the PlayStore is built from the source code provided here.

For phones without Google Play Services we do not yet have a solution, the app currently uses the Google ExposureNotification framework distributed as part of the Google Play Services.

**Closed by simonroesch** 2020-06-07 21:02 UTC
