### ISSUE TITLE
Synchronising report error (AGAEN39508)

### ISSUE THREAD

**Issue by mvszuri** [DP-3T/dp3t-app-android-ch#100] opened 2020-06-15 07:15 UTC
I have installed the SwissCovid app 1,5 week ago on my Android phone (Samsung A40, Android version 10). However, I am constantly getting an error message "An unexpected error has occurred while synchronising reports (AGAEN39508)" (see screenshot). I already tried uninstalling-reinstalling the app, but the error persisted.

![Screenshot_20200614-101946_SwissCovid](https://user-images.githubusercontent.com/37740095/84628240-8b3e8f00-aee8-11ea-955e-043cf858c8f5.jpg)

**Comment by simonroesch** [comment] 2020-06-15 11:26
Do you have access with ADB to the device? If so, could you please send me the output of 
`adb shell dumpsys activity provider com.google.android.gms.chimera.container.GmsModuleProvider | grep 'nearby_en'`

After uninstalling and reinstalling the app this error showed up immediately again or only after some time?

**Comment by mvszuri** [comment] 2020-06-15 12:14
"grep"  was not recognised, so now I ran the command without it: adb shell dumpsys activity provider com.google.android.gms.chimera.container.GmsModuleProvider. The complete output is attached. The error showed up immediately after reinstalling, but not immediately after installing the first time. After the first time installation, I first got an error about that the time on my device had to be set correctly. This error disappeared after a day and was replaced by the synchronisation error.

[output.txt](https://github.com/DP-3T/dp3t-app-android-ch/files/4780070/output.txt)

**Comment by simonroesch** [comment] 2020-06-16 20:02
Thanks for your info, unfortunately I have some follow up questions:
1) Do you have any other ExposureNotification apps installed? (Apps listed under Settings>Google>COVID-19 exposure notifications)

2) Can you confirm, that after uninstalling SwissCovid and installing it fresh from the PlayStore, the AGAEN39508 error shows up within the next few minutes again?

3) Is your device time set to use network time? (Settings > System > Date & time > Use network-provided time)

**Comment by mvszuri** [comment] 2020-06-17 06:21
No worries. Here are my answers:

1. No, SwissCovid it the only COVID-19 notification app
2. I uninstalled the app, restarted my phone and installed the app again. As soon as I completed the setup steps the app indicated an error (see screenshot below). However, the error code is different than the one above. After maybe a minute the error code changed to the one above (AGAEN39508).
3. Yes, my phone is set to use date and time provided by my network.

Let me know if you need any more information.
![Screenshot_20200617-081202_SwissCovid](https://user-images.githubusercontent.com/37740095/84862105-dab0c680-b072-11ea-88d2-35ce32c64e5e.jpg)

**Comment by uelino** [comment] 2020-06-19 16:49
@simonroesch same error here. Samsung S8, android 9. Notification comes back quite often and starts to be annoying. Best, Ueli

**Comment by simonroesch** [comment] 2020-06-19 20:33
This bug should be fixed in version 1.0.4-pilot that will be released in the next days.

**Comment by mvszuri** [comment] 2020-06-19 20:57
Great. Actually, I haven't had this error since this afternoon. Before the error message was always visible when I opened the app.



-------- Original message --------

**Comment by simonroesch** [comment] 2020-06-20 22:17
Please update to version 1.0.4-pilot now available in the PlayStore. After at most 24h after upgrading this error should no longer show up. Otherwise please reopen this issue!

**Comment by JPEckmann** [comment] 2020-06-24 18:31
same error on android samsung s6 phone. no other covid-apps. reinstalled, rebooted. same error again. (It did work yesterday)

**Comment by simonroesch** [comment] 2020-06-24 19:55
Can you please check if the error disappears tomorrow if you leave the app untouched? So no switching between other ExposureNotification apps, leaving SwissCovid as the active app.

**Comment by JPEckmann** [comment] 2020-06-24 19:59
Thanks. Genau. We can check tomorrow. I have adb, if needed.
(I am a science professor, so that may help  ;) )



On Wed, 24 Jun 2020, Simon Rösch wrote:

->Can you please check if the error disappears tomorrow if you leave the app untouched? So no switching between other ExposureNotification apps, leaving SwissCovid as the active app.
->
->-- 
->You are receiving this because you commented.
->Reply to this email directly or view it on GitHub:
->https://github.com/DP-3T/dp3t-app-android-ch/issues/100#issuecomment-649037105
->

**Comment by disearsch** [comment] 2020-06-26 05:30
Same Problem here with google pixel2. Deinstall - Restart - Install (V1.05)
Error AGAEN39508-2

**Comment by stefankoser** [comment] 2020-06-26 08:29
Same issue here: AGAEN39508.-2 Error on Samsung S10 short after installation

App Version 1.0.5 1.0.0

**Comment by simonroesch** [comment] 2020-06-26 09:05
Unfortunately, this issue is still happening on some devices. We would be very interested in bug reports to be able to see what exactly is happening and to forward them to Google. Unfortunately, Android bug reports can contain personal information, so please don't post them here. If you want to help us, see the instructions on https://developer.android.com/studio/debug/bug-report how to capture a bugreport and then send it to swisscovid@bag.admin.ch and ask them to forward it to the developer team.

**Comment by stefankoser** [comment] 2020-06-26 09:17
I have sent you the error report via email

**Comment by stefankoser** [comment] 2020-06-26 09:18
Can you clarify if the app works anyway or if this error prevents the app from functioning completely?

**Comment by JPEckmann** [comment] 2020-06-26 09:22
For me it works. Perhaps it is useful to see also when it works. Do bug 
reports say nything useful in this case?











On Fri, 26 Jun 2020, Simon Rösch wrote:

->Unfortunately, this issue is still happening on some devices. 
We would be very interested in bug reports to be able 
to see what exactly is happening and to forward them to Google. 
Unfortunately, Android bug reports can contain personal information, 
so please don't post them here. 

If you want to help us, see the instructions on 
https://developer.android.com/studio/debug/bug-report how to capture a bugreport and then send it to swisscovid@bag.admin.ch and ask them to forward it to the developer team.
->
->-- 
->You are receiving this because you commented.
->Reply to this email directly or view it on GitHub:
->https://github.com/DP-3T/dp3t-app-android-ch/issues/100#issuecomment-650074094

**Comment by caco3** [comment] 2020-06-26 11:32
Same on my phone (AGAEN39508.-2).
I had the pilot app now runing since several weeks and never saw this issue. Yesterday I updated to the official release and now this morning I saw this error.

A reboot of the phone did not fix it.

My phone automatically switches to flightmode (BT, Wifi, GPRS off) in the evening and back to normal in the morning. The error was first seen in the morning when it switched the com on again.

App version: 1.0.5, 1.0.0
Model: Sony 3113
Android: 9

**Comment by leosei** [comment] 2020-06-27 06:18
Same error with v1.0.5  of the app.
Sent full bug report to swisscovid@bag.admin.ch

**Comment by n0skill** [comment] 2020-06-27 09:49
Same issue here, will send the bug report if I can :)

**Comment by caco3** [comment] 2020-06-28 20:27
I uninstalled it and installed it again 2 days ago. The error did not show up again since then!

@simonroesch I generated a debug report beforehand, so if you still are interested, please let me know.

**Comment by fredinvdg** [comment] 2020-06-29 08:33
Hi, same error (AGAEN39508.-2) after removing, reboot, re-installed.
I had the test version before and it behaved the same way.
Old phone : SM-G389F  and old android: Android 6.01  
This configuration is a bit old, so it might be not relevant to the project, let me know if you d'like a bug report.

**Comment by JPEckmann** [comment] 2020-06-29 20:04
here is another observation: The app functions properly every morning, but the error seems to appear in the evening (around 7pm).
My phone is connected to the world only through wifi and in the evening I switch from the wifi in the office (university) to the one at home (swisscom)   : I do of course receive messages through my provider (migros)

Not sure this is relevant

**Comment by Botnic** [comment] 2020-06-30 07:32
This error appeared the first time today. The app is installed since release. Rebooting did not help.
- Time is set to network 
- No other Covid App installed
- Phone: Motorola G6 Android  9 (PPSS29.55-37-7-10)

**Comment by FlorianCassayre** [comment] 2020-06-30 10:31
For me the error appeared for the first time today when I rebooted my device, after having used it for a week without any issues. My device is a Galaxy S8+ running Android 9. I have also installed the French Covid app, but I do not activate them simultaneously.

**Comment by JPEckmann** [comment] 2020-07-01 08:25
sent anothe bug report. The error appears irregularly.

Can someone explain what exactly does notr work? Are my encounters not registered, or is it simply that I am not immediately advised if I have been in contact?

**Comment by FlorianCassayre** [comment] 2020-07-01 12:28
The error spawned during the whole day yesterday, and now it seems to be fixed on my side.

**Comment by arigo** [comment] 2020-07-02 12:52
Sent a bug report too.  It seems to work if I'm on the cell phone's data plan, and (as mentioned above) it stops working if I'm on wifi using Migros' Wingo provider.  Maybe the problem is that someone is filtering by IP address to let only Switzerland through, and for some reason Wingo's IPs are rejected?

**Comment by choralbari** [comment] 2020-07-02 17:22
I see the same error on my Moto e2.

**Comment by m3gg3** [comment] 2020-07-03 05:54
> Unfortunately, this issue is still happening on some devices. We would be very interested in bug reports to be able to see what exactly is happening and to forward them to Google. Unfortunately, Android bug reports can contain personal information, so please don't post them here. If you want to help us, see the instructions on https://developer.android.com/studio/debug/bug-report how to capture a bugreport and then send it to [swisscovid@bag.admin.ch](mailto:swisscovid@bag.admin.ch) and ask them to forward it to the developer team.

@simonroesch 
Same problem here on my Samsung S20 5G with May 2020 Patchlevel on Android 10

**Comment by arigo** [comment] 2020-07-03 06:30
> Sent a bug report too. It seems to work if I'm on the cell phone's data plan, and (as mentioned above) it stops working if I'm on wifi using Migros' Wingo provider. Maybe the problem is that someone is filtering by IP address to let only Switzerland through, and for some reason Wingo's IPs are rejected?

No, that theory is wrong, I'm seeing the problem on the cell phone's data plan too.  (Additionally it tends to crash System UI and reset my phone's background image, a few times a day.)

**Comment by JPEckmann** [comment] 2020-07-03 13:41
Dear Simonroesch: Can you tell us what exactly happens if this famous 
error occurs?
Is it that the connection to the database is just "temporarily" broken, or 
is it that the vicinity test of the app is broken.

I consider the first case sport of irrelevant, and the second case is 
serious. 

Does bag actually forward all the crash reports people like me are 
sending?

Thanks for a "professional" update.

**Comment by m3gg3** [comment] 2020-07-03 14:14
> This bug should be fixed in version 1.0.4-pilot that will be released in the next days.

The same bug here in 1.0.5 please fix it

**Comment by m3gg3** [comment] 2020-07-05 09:21
> > This bug should be fixed in version 1.0.4-pilot that will be released in the next days.
> 
> The same bug here in 1.0.5 please fix it

seems like you fix that in the background, it works now! without an app update, very scary

**Comment by saccamor** [comment] 2020-07-06 16:41
> Same on my phone (AGAEN39508.-2).
> I had the pilot app now runing since several weeks and never saw this issue. Yesterday I updated to the official release and now this morning I saw this error.
> 
> A reboot of the phone did not fix it.
> 
> My phone automatically switches to flightmode (BT, Wifi, GPRS off) in the evening and back to normal in the morning. The error was first seen in the morning when it switched the com on again.
> 
> App version: 1.0.5, 1.0.0
> Model: Sony Xperia XA2 (H3113)
> Android: 9

Same problem. Since today I have an AGAEN39508.-2 error after turning off flightmode.

App version: 1.0.5
Model: Google Pixel 3
Android: 10

**Comment by tkuenzle** [comment] 2020-07-07 15:11
Same problem since today. Same phone, also after turning off flightmode.

App version: 1.0.5
Model: Google Pixel 3
Android: 10

**Comment by ville87** [comment] 2020-07-09 06:06
Same here, since today I have AGAEN39508.-2 on Google Pixel 4, Android 10. Restart did not solve the issue. Uninstall and Install of the App solved the problem (at least for the moment...)

**Comment by rapmue** [comment] 2020-07-09 13:09
Same here, sometimes it's working, but most of the time there is this error. I had the app installed since the early preview and this error never showed up. Since Sunday it's more or less constantly present. (Yesterday, the app was able to synchronize somehow and the error showed up this morning after I left flight mode)

App version: 1.0.5
Model: Google Nexus 5X
Android: 8.1.0

**Comment by KIC** [comment] 2020-07-09 14:39
same here one+ 7 pro
well it used to work fine until recently this week

**Comment by wauwau0977** [comment] 2020-07-13 05:49
same here, pixel 3 xl, standard installation

**Comment by noipser** [comment] 2020-07-13 06:16
Hi,
I installed the SwissCovid App on the first day it was released and did not have any problems until this morning.
Now I got the AGAEN39508.-2 Error as well. I did not change anything on the phone.

I could install adb for debugging if needed.

My Phone is a "HTC U11 life" with Android 10, Security-Update 01.06.2020

**Comment by lenaulrich** [comment] 2020-07-14 11:38
I installed SwissCovid on the day it was released and did not have any issues until this morning. I usually put my phone in flight mode during the night. This morning I had the error: AGAEN39508.-2
Reinstallation of the app did not solve the issue.

SwissCovid App: Version 1.0.5, 1.0.0
Phone: Samsung Galaxy S10 with Android 10, Android Security Patch Level: June 1, 2020

**Comment by wauwau0977** [comment] 2020-07-14 11:58
yes, may be a pattern... i go to flight mode too

**Comment by valentinaIHEID** [comment] 2020-07-15 09:24
Same error. It started yesterday. I tried to uninstall and install the app again, but the error did not disappear. Here are mi specs:
version: 1.0.5
updated on 18 Jun 2020
operates on an Android.

**Comment by BorntraegerMarc** [comment] 2020-07-17 13:35
![Screenshot_20200717-153244](https://user-images.githubusercontent.com/7549295/87791737-14781700-c843-11ea-9baa-c00f780ee97c.jpg)

**Comment by simonroesch** [comment] 2020-07-17 19:20
This issue was fixed as part of version [1.0.7](https://github.com/DP-3T/dp3t-app-android-ch/releases/tag/1.0.7) that will be available in the PlayStore next week as staged rollout.

The AGAEN39508 indicated a rate limit error on the ExposureNotification API. This could happen if the EN API resulted in an unexpected error: the DP3T-SDK implementation did not count this call to the rate limit count and retried the same call on the next sync. Unfortunately, the ExposureNotification API counts all calls towards the rate limit, including those resulting in an unexpected error (for example https://github.com/DP-3T/dp3t-app-android-ch/issues/133). This has been fixed with https://github.com/DP-3T/dp3t-sdk-android/pull/178

**Closed by simonroesch** 2020-07-17 19:20 UTC
